# Generated by Django 5.2.7 on 2026-10-01 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_servicerequest_requested_time_platformnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnotification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='platformnotification',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.servicerequest'),
        ),
    ]
